#ifndef ENUM_CODES_HXX_INCLUDED____
#define ENUM_CODES_HXX_INCLUDED____
enum class KEYS_TS{
  CTRL_X = 24,
  CTRL_N = 14,
  CTRL_P = 16,
  CTRL_D = 4,
  ESC = 27,
  CTRL_U = 21,
  CTRL_K = 11,
  BACKSPACE_NORMAL = 127,
  BACKSPACE_ARROWS = 7
};
enum class EXITCODE_TS{
  ALL_GOOD = 0,
  RERUN_THIS_MODE = 1,
  TO_MENU = 2,
};
#endif //  ENUM_CODES_HXX_INCLUDED____
